### ISSUE TITLE
v0.29.2 release

### ISSUE THREAD

**Issue by roparz** [meilisearch/meilisearch-aws#218]
Hi,

Do you plan to create a new AMI for v0.29.2?
I'm facing issues with a bug fixed in this version.
> Prevent duplicate documents in the search route (https://github.com/meilisearch/meilisearch/pull/3047 and https://github.com/meilisearch/milli/pull/698) @Kerollmops

Thanks.

**Comment by alallema** [comment]
Hello @roparz 

We just released v0.29.2, yesterday 😊
I will do my best to do it before the end of this week, otherwise next week.
In the worst case scenario, end of November, but should be done before.

Thanks for reaching us and using Meilisearch.

**Comment by roparz** [comment]
Thank you 🙏 
I didn't realize that it was released yesterday.

**Comment by roparz** [comment]
Hi,
I'm really sorry to insist but we need this version to fix huge GDPR issues.
We are using meilisearch to search for users against different companies and some of these users can be found were they should not...
Is there a way to build and push my own image based on this version?
Thanks.

**Comment by brunoocasali** [comment]
Hi @roparz, I'm sorry, but this was not done yet. @alallema is on sick leave, and she will be back next week. We will try to prioritize it soon :)

**Comment by alallema** [comment]
Hi @roparz,
I just published the new image for v0.29.2 on aws! 🎉 
Let me know if you have any problems with it.
I will close this issue. 
![Screenshot 2022-11-28 at 13 37 06](https://user-images.githubusercontent.com/16155041/204279783-3435dfe9-9c1b-4c10-938e-1d34fc1a8cb6.png)

**Comment by roparz** [comment]
Thank you but I can only see v0.28.1 (this one has performance issues handling queues) and v0.30.0 (I have issues with filters with this one: https://github.com/meilisearch/meilisearch/issues/3178).
Maybe it has been removed when pushing v0.30.0? Can you put it back?
Thanks.

<img width="1235" alt="Capture d’écran 2022-12-01 à 17 37 40" src="https://user-images.githubusercontent.com/204520/205108906-b3c7f68c-4767-4aa7-8b34-4ccdf52e3de2.png">

**Comment by alallema** [comment]
Hi @roparz,
Normally it should be there, I left these 3:
![Screenshot 2022-12-01 at 17 49 30](https://user-images.githubusercontent.com/16155041/205111641-21c342aa-6fd3-4964-83e1-7a1d3f2f294a.png)
Can you tell me in which zone you searching?

**Comment by alallema** [comment]
It's should work now! Sorry the AMI was Private ... oops

**Comment by roparz** [comment]
I can see it now.
Thank you so much for your quick response!
