### ISSUE TITLE
0.30.5 aws community edition update

### ISSUE THREAD

**Issue by ozgurhangisi** [meilisearch/meilisearch-aws#242]
Hello,

The latest version of meilisearch is 0.30.4 on aws community edition in frankfurt region.  Which has critical document duplication  bug on search.  Is is possible to update the latest version to 0.30.5? 

Thanks,
Özgür.

**Comment by alallema** [comment]
Hi @ozgurhangisi,

Sorry for the inconvenience. Yes, the new version should be published soon I will try to do it this week. I'll let you know when it's done.

**Comment by alallema** [comment]
Hi @ozgurhangisi,
The AMI is published so I will close this issue. Feel free to reopen it if there is a problem.
