### ISSUE TITLE
1.01 aws community edition update

### ISSUE THREAD

**Issue by ozgurhangisi** [meilisearch/meilisearch-aws#269]
Hello,

The latest version of meilisearch is 1.0 on aws community edition in frankfurt region. Version 1.01 has pagination bug fix. Is it possible to update community edition version to 1.01?

Thanks,
Özgür.

**Comment by alallema** [comment]
Hi @ozgurhangisi,
There should be a new release of `v1.0.2` by the beginning of next week that's why v1.0.1 is not yet online I will put directly to the last one as soon as it is available.
Sorry for the inconvenience.

**Comment by alallema** [comment]
I am closing this issue, Meilisearch `v1.0.2` AMI is available on AWS
