### ISSUE TITLE
Update aws community edition to 1.1.1

### ISSUE THREAD

**Issue by ozgurhangisi** [meilisearch/meilisearch-aws#297]
Hello,

The latest version of meilisearch is 1.1.0 on aws community edition in frankfurt region. Version 1.1.1 has a few bug fixes and meili team recommend to use 1.1.1 instead of 1.1.0. Is it possible to update aws community edition to 1.1.1

Thanks,
Özgür.

**Comment by alallema** [comment]
Hi @ozgurhangisi,
The last image with v.1.1.1 is now available 😊
