### ISSUE TITLE
running AMI EC2 instance doesn't seem to connect to Http or Https

### ISSUE THREAD

**Issue by yukkeechang** [meilisearch/meilisearch-aws#36]
After following https://docs.meilisearch.com/create/how_to/aws.html#_8-set-and-download-key-pair to create a EC2 instance and following the steps (same security rules, specs, etc) the running instance's Public IPv4 DNS and address doesn't connect

**Comment by curquiza** [comment]
Hello @yukkeechang!

Thanks for your feedback. Can you tell us what do you mean by your instance not being connected? how are you trying to reach it?

**Comment by yukkeechang** [comment]
very dumb error: was trying to connect my public IPv4 through https not http on browser. I was so confused because curl -v http://<my IPv4>/health was working..which meant I wasn't reaching it the right way
