### ISSUE TITLE
Not able to find MelliSearch AMI in EC2

### ISSUE THREAD

**Issue by apijay** [meilisearch/meilisearch-aws#42]
I no longer can find MelliSearch AMI in community AMI

**Comment by alallema** [comment]
Hi @apijay,
I just checked and I got it when I click on 2 results in Community AMIs.
What did you got ?
<img width="1212" alt="Screenshot 2021-06-23 at 10 08 29" src="https://user-images.githubusercontent.com/16155041/123061791-3fcc9400-d40c-11eb-8733-3b67988970b1.png">
<img width="1213" alt="Screenshot 2021-06-23 at 10 08 43" src="https://user-images.githubusercontent.com/16155041/123061810-42c78480-d40c-11eb-8019-140e99bc4869.png">

**Comment by alallema** [comment]
I'm closing this issue because it is outdated. Feel free to reopen it if you need it.
