### ISSUE TITLE
Default config for max opened files

### ISSUE THREAD

**Issue by neylsongularte** [meilisearch/meilisearch-aws#51]
I got this error using the image:

```
MeiliSearch ApiException: Http Status: 500 - Message: Too many open files (os error 24) - Error code: internal - Error type: internal_error - Error link: https://docs.meilisearch.com/errors#internal
```

**Comment by hungdhm-0574** [comment]
@alallema  hi, is this problem resolved ? i still face with this error with meilisearch version 0.28.1

**Comment by alallema** [comment]
Hi @hungdhm-0574,
Depending on your dataset size it could [cf doc](https://docs.meilisearch.com/learn/advanced/known_limitations.html#large-datasets-and-internal-errors). But if you encounter this error in another situation than the one described I recommend you to open an issue on `meilisearch` repository directly.
