### ISSUE TITLE
net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by gadangmadhulika** [meilisearch/meilisearch-aws#58]
Hi, I created MeiliSearch instance in AWS and passed data through strapi but i could see authorization bearer issue

{"message":"The Authorization header is missing. It must use the bearer authorization method.","code":"missing_authorization_header","type":"auth","link":"https://docs.meilisearch.com/errors#missing_authorization_header"}

**Comment by alallema** [comment]
Hi @gadangmadhulika,
Yes, we just release the last version of Meilisearch v0.25.0 which needs this new `Authorization bearer`. You should use the `v0.5.0` of Strapi plugin with it. See [more details here](https://github.com/meilisearch/strapi-plugin-meilisearch/releases/tag/v0.5.0). Or use the `v0.24.0` of Meilisearch with your actual version of Strapi plugin.

**Comment by gadangmadhulika** [comment]
HI, Im receiving the below error in the front end and iam using "strapi-plugin-meilisearch": "^0.5.0",

MeiliSearchCommunicationError

**Comment by bidoubiwa** [comment]
> MeiliSearchCommunicationError
Should be linked to your MeiliSearch instance! 

Could you give the whole error message?

**Comment by gadangmadhulika** [comment]
HI
Receiving the below error as we tried following the documentation(https://docs.meilisearch.com/learn/cookbooks/aws.html ) and followed the steps but got stuck with the below issue. Please Guide.
net::ERR_CONNECTION_REFUSED

**Comment by gadangmadhulika** [comment]
Hi, Issue got resolved, when created a domain with SSL.

**Comment by alallema** [comment]
Hi @gadangmadhulika,
Glad you solved it! Yes, You can only use `HTTPS` if you have enabled `SSL` certificates. I close this issue then.
